# -*- coding: utf-8 -*-
{
    'name': 'VNOptic B2B Portal',
    'version': '18.0.1.0.0',
    'summary': 'Portal B2B đại lý: đặt đơn, công nợ',
    'category': 'Sales/Portal',
    'author': 'VNOptic',
    'depends': [
        'base',
        'mail',
        'portal',
        'sale_management',
        'account',
        'website',
        'vnop_sale_channel',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence_data.xml',
        'data/menu_data.xml',
        'views/res_partner_views.xml',
        'views/order_request_views.xml',
        'templates/portal_layout.xml',
        'templates/portal_footer.xml',
        'templates/website_header.xml',
        'templates/portal_home.xml',
        'templates/portal_orders.xml',
        'templates/portal_financial.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'vnop_b2b_portal/static/src/scss/portal_branding.scss',
            'vnop_b2b_portal/static/src/scss/vn_footer.scss',
            'vnop_b2b_portal/static/src/js/order_picker.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
