{
    'name': 'VNOptic - POS Bán Lẻ Mắt Kính',
    'version': '18.0.3.0.0',
    'summary': 'POS chuyên ngành kính + cấu hình kế toán chuẩn VN (TT200) + sản phẩm/khách mẫu',
    'category': 'Point of Sale',
    'author': 'VNOptic',
    'license': 'LGPL-3',
    'depends': [
        'point_of_sale',
        'l10n_vn',
        'vnop_sale_channel',
        'vnop_sync',
    ],
    'data': [
        'security/pos_optical_security.xml',
        'security/ir.model.access.csv',
        'data/pos_payment_method_data.xml',
        'data/pos_category_data.xml',
        'data/pos_bill_data.xml',
        'data/ir_sequence_data.xml',
        'data/product_template_data.xml',
        'data/res_partner_data.xml',
        'views/pos_config_views.xml',
        'views/pos_order_views.xml',
        'views/product_template_views.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'vnop_pos_optical/static/src/overrides/components/prescription_popup/prescription_popup.js',
            'vnop_pos_optical/static/src/overrides/components/prescription_popup/prescription_popup.xml',
            'vnop_pos_optical/static/src/overrides/components/prescription_popup/prescription_popup.scss',
            'vnop_pos_optical/static/src/overrides/components/orderline/orderline.xml',
            'vnop_pos_optical/static/src/overrides/models/pos_order_line.js',
            'vnop_pos_optical/static/src/overrides/models/pos_store.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
