{
    'name': 'Product Sync from Server',
    'version': '18.0.1.0.9',
    'category': 'Inventory',
    'depends': ['base', 'stock', 'product', 'purchase', 'account', 'base_import', 'l10n_vn', 'queue_job', 'queue_job_cron_jobrunner'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_import_export_templates.xml',
        'data/uom_data.xml',
        'data/product_category_data.xml',
        'data/product_brand_data.xml',
        'views/product_sync_views.xml',
        'views/product_brand_views.xml',
        'views/product_warranty_views.xml',
        'views/product_tree_common_views.xml',
        'views/product_category_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_supplier_views.xml',
        'views/product_template_kanban_views.xml',
        'views/product_group_views.xml',
        'views/product_lens_config_views.xml',
        'views/product_master_data_config_views.xml',
        'views/product_opt_lens_views.xml',
        'views/server_connector_views.xml',
        'views/product_export_template_wizard.xml',
        'views/queue_job_import_buttons.xml',
        'views/vnop_sync_purchase_config_menus.xml',
    ],
    'external_dependencies': {
        'python': ['requests', 'Pillow', 'python-dotenv', 'openpyxl', 'xlsxwriter']
    },
    'assets': {
        'web.assets_backend': [
            'vnop_sync/static/src/scss/product_kanban_modern.scss',
            'vnop_sync/static/src/js/preview_long_text.js',
            'vnop_sync/static/src/js/product_export_cog_menu.js',
            'vnop_sync/static/src/js/import_model_queue_patch.js',
            'vnop_sync/static/src/js/import_action_queue_patch.js',
            'vnop_sync/static/src/xml/product_export_cog_menu.xml',
            'vnop_sync/static/src/js/product_kanban_buttons.js',
            'vnop_sync/static/src/xml/product_kanban_buttons.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}
