{
    "name": "Row Number in List View",
    "version": "18.0.1.0.5",
    "summary": "Show row number (#) column in backend list views.",
    "category": "Extra Tools",
    "depends": [
        "web",
        "account",
        "account_bank_statement_import",
        "account_online_synchronization",
        "purchase",
        "sale",
        "sale_loyalty",
        "stock",
        "website",
        "resource",
    ],
    "data": [],
    "assets": {
        "web.assets_backend": [
            "rowno_in_tree/static/src/views/list/list_render.xml",
            "rowno_in_tree/static/src/views/list/list_renderer.js",
            "rowno_in_tree/static/src/views/list/list_renderer.scss",
        ],
    },
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False,
}
