# -*- coding: utf-8 -*-
{
    'name': 'VNOptic - Trả hàng lỗi từ đại lý',
    'version': '18.0.1.1.0',
    'category': 'Sales/Sales',
    'summary': 'Quy trình trả hàng lỗi từ đại lý: tạo yêu cầu, duyệt nghiệp vụ, QC, nhập kho, cấn trừ công nợ',
    'depends': [
        'mail',
        'sale_stock',
        'account',
        'stock',
        'vnop_sale_channel',
        'vnop_stock',
        'vnop_warranty',
    ],
    'data': [
        'security/return_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence.xml',
        'data/ir_config_parameter.xml',
        'data/stock_location_data.xml',
        'data/return_defect_group_data.xml',
        'data/return_reason_data.xml',
        'wizard/return_qc_classify_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/vnop_return_reason_views.xml',
        'views/vnop_return_request_views.xml',
        'views/sale_order_views.xml',
        'views/menu.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
